version: '3'

services:

  generator:
    build: ./generator
    environment:
      KAFKA_BROKER_URL: broker:9092
      TRANSACTIONS_TOPIC: queueing.transactions
      TRANSACTIONS_PER_SECOND: 1000
      KAFKA_DELETE_TOPIC_ENABLE: "true"

  classifier:
    build: ./classifier
    environment:
      KAFKA_BROKER_URL: broker:9092
      TRANSACTIONS_TOPIC: queueing.transactions
      PREDICT_TOPIC: streaming.transactions.predict

networks:
  default:
    external:
      name: kafka-network